awtterpip/bevy_oxr

Cargo.toml

Without this, it errors on macos. My guess is because by default, vulkan backend is not enabled on mac.
```
Compiling bevy v0.12.0-dev (https://github.com/awtterpip/bevy#96876698)
Compiling color-eyre v0.6.2
Compiling bevy_openxr v0.1.0 (https://github.com/awtterpip/bevy_openxr?rev=9361991a5f
error[E0432]: unresolved import `wgpu_hal::api::Vulkan`
--> /Users/ryan/.cargo/git/checkouts/bevy_openxr-1dedcf84dfa11c13/9361991/src/graphics
|
36 |     use wgpu_hal::{api::Vulkan as V, Api};
|                    ^^^^^^^^^^^^^^^^ no `Vulkan` in `api`
|
= help: consider importing one of these items instead:
crate::Swapchain::Vulkan
crate::xr::Vulkan
openxr::Vulkan
wgpu::Backend::Vulkan
note: found an item that was configured out
--> /Users/ryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu …
```

Explicitly ask for vulkan

---

src/lib.rs

Should fix #19
I somehow didn't copy this part from [android](https://github.com/awtterpip/bevy_openxr/tree/android) branch here, to my android PR #18.
So yes, on quest 2 I see same error sometimes without this patch.

xr_wait_frame lock match instead of unwrap

---

examples/android/README.md
examples/android/manifest.yaml

cargo-apk is deprecated in favour of xbuild https://github.com/rust-mobile/xbuild
https://github.com/rust-mobile/cargo-apk/commit/558adff4f77740bc3a9353e2a8350064fa2942bd
I tried to make it work with xbuild. And it required to write manifest.yaml.
So my proposal it to just add this manifest.yaml to the example, and it starts working with xbuild.

Android example xbuild

---

src/xr_input/xr_camera.rs

This PR ports [get_frustum_corners](https://github.com/bevyengine/bevy/pull/9226/files#diff-17834fc6389be55867ad34d896b05322c64245f8a46da89ba932e99d44ba305dR165-R181) to `XRProjection`, as it's a new required method of `CameraProjection`. I do not do `.abs()` like the original code, because the _[original](https://github.com/bevyengine/bevy/pull/7064/files#diff-c60eda8fbc401d2abd66241ba0ece700ad17d8ae3acef6a6196652ca70b4fa4cR400-R408)_ original asserts that the near and far are negative and then calls `.abs()`, while the [new code](https://github.com/bevyengine/bevy/pull/9226/files#diff-c60eda8fbc401d2abd66241ba0ece700ad17d8ae3acef6a6196652ca70b4fa4cR450-R457) negates the Z before passing it in, hopefully meaning that it's always positive. (I think this means the `.abs()` in the upstream …

Implement get_frustum_corners

---

.github/workflows/build.yml
Cargo.toml
README.md
src/graphics/mod.rs

This attempts to resolve the common issue with the `CMake error: ...` that people keep running into by making use of platform-specific dependency changes in the `cargo.toml`.

Make `openxr` features platform agnostic to fix `CMake error: ...` common issue.

---

src/lib.rs

Fixes #26 
It would be preferable if we only ignored ERROR_SESSION_NOT_RUNNING and continued panicking on other errors, however the constant is in a private module in the openxr-sys crate and my Rust knowledge is lacking on how to extract it.

Ignore end_frame error

---

Cargo.toml

This way a link to the repo shows up on crates.io

add repository to package metadata

---

Cargo.toml

Just 1 commit to fix the repository link

Update Cargo.toml to change bevy_openxr to bevy_oxr in GitHub link

---

examples/android/src/lib.rs
src/lib.rs

and disable pipelined rendering by default

expose sync pipeline comp, pipelined rendering experimental

---

src/lib.rs

VSync limits the max FPS to 60 on Quest 3. This PR disables VSync, allowing FPS up to 90-100 (tested in the android example).

Disabled VSync on Android

---

crates/bevy_openxr/src/openxr/init.rs

Without this line, when compiles to android, it will immediately crash after app started. after adding this line, issue resolved.

fix android "null pointer dereference"

---

crates/bevy_openxr/src/openxr/action_binding.rs
crates/bevy_openxr/src/openxr/action_set_attaching.rs
crates/bevy_openxr/src/openxr/init.rs
crates/bevy_openxr/src/openxr/mod.rs
crates/bevy_xr/src/session.rs

adds the required systems to allow for multiple frameworks to use the OpenXR actions
One potential issue might be that we have to sync the action sets in this crate, but i can't test that without a second framework.
this also adds a simple event for session status changes

Refactor - Generic system for binding sugesstion and action set attaching

---

LICENSE-APACHE
LICENSE-MIT
README.md

For legal reasons, projects generally should make explicit that *inbound* contributors agree to license the code as both licenses. And outbound lets you pick.
Drawn from bevy's readme.

add license files and section in README

---

crates/bevy_openxr/Cargo.toml

idk if anyone else with a mac has run into this issue, but there errors inside of [vulkan.rs](https://github.com/awtterpip/bevy_oxr/blob/3654b36e76d51aa53e0ceff7a700c1b166a5c98b/crates/bevy_openxr/src/openxr/graphics/vulkan.rs). Specifically at `use wgpu_hal::api::Vulkan;`, i get 
```
unresolved import `wgpu_hal::api::Vulkan`
no `Vulkan` in `api`
```
and then it when diving into the crate, it says Vulkan has been configured out.
I do have the VulkanSDK installed + MoltenVK, yet the same error. So this seems to be easiest way to use vulkan on a mac...?

add 'vulkan-portability' feature to wgpu when target family is unix (MacOS support)

---

crates/bevy_xr/src/camera.rs

This system is required to avoid a crash when cascading shadow maps are used.

added system for cascading shadow maps

---

Cargo.toml
crates/bevy_openxr/src/openxr/action_set_syncing.rs
crates/bevy_openxr/src/openxr/features/handtracking.rs
crates/bevy_openxr/src/openxr/features/overlay.rs
crates/bevy_openxr/src/openxr/init.rs
crates/bevy_openxr/src/openxr/mod.rs
crates/bevy_openxr/src/openxr/reference_space.rs
crates/bevy_openxr/src/openxr/spaces.rs
crates/bevy_xr/src/session.rs
crates/bevy_xr/src/spaces.rs

Add Backend Specific `session_running` and `session_available` to allow for non OpenXR backends while compiling for something other than wasm
Add SpaceFlags to bevy_mod_xr to detect loss of tracking without needing to depend on bevy_mod_openxr directly

Backend Specific RunConditions and Space Flags in xr crate

---

crates/bevy_openxr/examples/tracking_utils.rs
crates/bevy_xr_utils/src/tracking_utils.rs

Made the default bindings a pub function so the end user can call it if they want. This resolves the issue while I investigate better solutions.

Remove default bindings

---

crates/bevy_openxr/src/openxr/resources.rs

apparently steamvr is a pain on all platforms, not only linux!

downgrade to the newest OpenXR 1.0 to accommodate legacy runtimes like SteamVR

---

crates/bevy_openxr/examples/android/Cargo.toml

Bevy 0.15 changed the default `Activity` for Android projects to be `GameActivity`, which breaks Quest builds. Updated the Android example to use the `android-native-activity` feature instead of `android-game-activity`.

Update the Android example to use NativeActivity instead of GameActivity

---

crates/bevy_openxr/src/openxr/mod.rs
crates/bevy_openxr/src/openxr/render.rs

Sets all entities with the `XrCamera` component to use the correct render texture, allowing XrCameras to be spawned much easier. Also added an option to the `OxrRenderPlugin` to allow enabling or disabling auto spawning of cameras.

Update camera texture view

---

Cargo.lock
crates/bevy_openxr/Cargo.toml
crates/bevy_openxr/src/openxr/graphics/vulkan.rs

This makes the wgpu init closer to the normal init in wgpu, this should fix issues where apps made pretty reasonable assumptions about the hardware while wgpu thought that the hardware only supports the bare minimum

More correct wgpu init

---

crates/bevy_openxr/examples/actions.rs
crates/bevy_openxr/src/openxr/init.rs
crates/bevy_xr/src/session.rs

allows crate consumers to react to the destruction to, for example, start another session

add XrSessionDestroyedEvent 

---

crates/bevy_openxr/examples/3d_scene.rs

the background is black on other runtimes but i need a better EnviromentBlendMode api to fix that

fix 3d_scene example on runtimes that aren't WiVRn
