awtterpip/bevy_oxr

src/xr_input/oculus_touch.rs

I fixed the tracking being backwards, and the aim space being wrong.
I also made the thumbstick members public so they can actually be used in external crates

fixed handedness issues and made thumbstick struct members public

---

examples/xr.rs
src/xr_input/debug_gizmos.rs
src/xr_input/mod.rs

I added the system to draw the debug gizmos.
I am not sure what makes the most sense, but this runs and is in its own file.
feed back would be welcome, I haven't done much rust development before.

Added debug_gizmos system

---

src/lib.rs

fixing compiling errorr from update from upstreams

fix compile

---

Cargo.toml
examples/xr.rs
src/xr_input/debug_gizmos.rs
src/xr_input/mod.rs
src/xr_input/prototype_locomotion.rs
src/xr_input/trackers.rs
src/xr_input/xr_camera.rs

this tackles two things:
1.  how to spawn and mark entities for openxr tracking
2. a prototype locomotion system configurable via bevy resource
both of these are very rough, and will need another pass before I consider them complete, however both are functional

Prototype locomotion and refactoring openXR tracking

---

.github/workflows/build.yml
Cargo.toml

Checks are optional for now.
Builds is only on linux, I have a template in [lux](https://github.com/raffaeleragni/lux/blob/master/.github/workflows/build.yml) for also win+mac if we need it.

Basic automated build

---

Cargo.toml
examples/xr.rs
src/xr_input/interactions.rs
src/xr_input/mod.rs
src/xr_input/prototype_locomotion.rs
src/xr_input/trackers.rs

this is a rough pass at interactions, it will require more work but it is functional for now.
known issues:
1. cant have direct and ray interactors on the same entity
2. multiple interactors can select the same interactable
3. hovering over an interactable selected by a socket interactor changes its state to hover, the socket interactor should be setting it to selected

Interactions

---

Cargo.toml
examples/android/Cargo.toml

use stable version now that is released

bevy upgrade 0.12

---

src/graphics/vulkan.rs
src/lib.rs
src/xr_input/debug_gizmos.rs
src/xr_input/hand.rs
src/xr_input/handtracking.rs
src/xr_input/mod.rs

Add Really basic Hand Tracking support

Add Hand tracking

---

examples/demo/src/lib.rs
examples/xr.rs
src/lib.rs
src/xr_input/actions.rs
src/xr_input/debug_gizmos.rs
src/xr_input/hand.rs
src/xr_input/mod.rs
src/xr_input/oculus_touch.rs
src/xr_input/prototype_locomotion.rs
src/xr_input/trackers.rs

Rework the lower level OpenXR action system to allow the adding of actions and bindings in any system in the Startup schedule.
But i don't know if this should actually be merged since it removes a lot of compile time checking.

Rework the oxr action system

---

examples/demo/src/lib.rs

This adds some basic stuff to disable physical interactions with the hands while the interaction system is interacting with something. This makes dropping grabbable objects much better, because the object is not ejected from your hand.

Improved interactions

---

src/xr_input/debug_gizmos.rs
src/xr_input/hands/emulated.rs
src/xr_input/trackers.rs

this makes changes to a few systems replacing unwraps with matches
it also log spams in debug why these systems aren't doing what a developer would expect.
this resolves https://github.com/awtterpip/bevy_openxr/issues/45

Optional controllers

---

examples/globe.rs
src/xr_input/prototype_locomotion.rs

I also added a demo where you can walk around on a sphere.

Enable locomotion to handle arbitrary rotations of the view space

---

src/xr_init.rs
src/xr_input/actions.rs
src/xr_input/hands/emulated.rs
src/xr_input/oculus_touch.rs

some small XrSetup Scheduling changes and a small type change on Setup Actions and Setup Action Sets

Small Changes to make Creating Crates that interact with the action system easier

---

src/lib.rs
src/xr_input/actions.rs
src/xr_input/mod.rs

Also Fixed an issue where a system was wrongly not annotated as xr_only

Add Vec2Conv helper and Display warning with message when openxr fails to load

---

Cargo.toml
src/lib.rs

Auto fallback to flat when using wasm

do not compile openxrs for wasm

---

src/xr_init/mod.rs

tested on windows with and without steamvr

fix panic when trying to start a session without an instance

---

crates/bevy_openxr/Cargo.toml
crates/bevy_openxr/src/openxr/error.rs
crates/bevy_openxr/src/openxr/graphics.rs
crates/bevy_openxr/src/openxr/graphics/d3d12.rs
crates/bevy_openxr/src/openxr/mod.rs
flake.nix

adds dx12 support
should be tested by preferably at least two people before merged

D3d12 support

---

crates/bevy_openxr/src/openxr/features/handtracking.rs

push left hand bones as children of root as well

---

crates/bevy_openxr/examples/transform_utils.rs
crates/bevy_openxr/src/openxr/action_binding.rs
crates/bevy_xr_utils/src/lib.rs
crates/bevy_xr_utils/src/transform_utils.rs
crates/bevy_xr_utils/src/xr_utils_actions.rs

This implements some events to simplify setting the player position and rotation.

Transform utils

---

crates/bevy_openxr/examples/actions.rs
crates/bevy_openxr/examples/raw_actions.rs
crates/bevy_openxr/src/openxr/action_set_attaching.rs
crates/bevy_openxr/src/openxr/features/handtracking.rs
crates/bevy_openxr/src/openxr/helper_traits.rs
crates/bevy_openxr/src/openxr/layer_builder.rs
crates/bevy_openxr/src/openxr/mod.rs
crates/bevy_openxr/src/openxr/reference_space.rs
crates/bevy_openxr/src/openxr/render.rs
crates/bevy_openxr/src/openxr/session.rs
crates/bevy_openxr/src/openxr/spaces.rs
crates/bevy_xr/src/lib.rs
crates/bevy_xr/src/spaces.rs
crates/bevy_xr/src/types.rs
crates/bevy_xr_utils/src/xr_utils_actions.rs

creates in implements a potential new Space api which should also work for webxr to some capacity

RFC: New Space Api

---

crates/bevy_xr/src/camera.rs

This reverts commit 7c400c3dc82a1fe0c7854f7caf76e65e3c831d74.
fixing my mistake

Revert "Update camera.rs"

---

crates/bevy_openxr/src/openxr/features/handtracking.rs
crates/bevy_openxr/src/openxr/init.rs
crates/bevy_openxr/src/openxr/spaces.rs
crates/bevy_xr/src/spaces.rs

we also might want to hookup other instance events in the future

Expose Velocities and SpaceFlags and add InteractionProfile changed event

---

.github/workflows/ci.yaml
crates/bevy_openxr/Cargo.toml
crates/bevy_openxr/src/openxr/features/handtracking.rs
crates/bevy_webxr/Cargo.toml
crates/bevy_xr/Cargo.toml
crates/bevy_xr/src/hands.rs
crates/bevy_xr_utils/Cargo.toml
crates/bevy_xr_utils/src/lib.rs
crates/bevy_xr_utils/src/tracking_utils.rs
crates/bevy_xr_utils/src/xr_utils_actions.rs

move spawn_hand_bones from openxr to xr and add spawn handtracker command
also adds extremely simple CI

add CI and move more hand related things into bevy_mod_xr

---

Cargo.lock
Cargo.toml
crates/bevy_xr/src/hands.rs

fixes a stupid little issue i sadly overlooked before release of v0.1.0

hand tracker spawn side hotfix

---

Cargo.toml
crates/bevy_openxr/src/openxr/graphics/vulkan.rs

enable wgpu device feature needed for bevy

---

crates/bevy_openxr/src/openxr/features/passthrough.rs
crates/bevy_openxr/src/openxr/graphics/vulkan.rs

This works on macOS using the Meta XR Simulator using a patched version of MoltenVK.
PS: SPIRV-Cross patch has also been submitted to Khronos.

Ensure that it also works using Meta XR Simulator in macOS

---

crates/bevy_openxr/examples/3d_scene.rs
crates/bevy_openxr/examples/overlay.rs
crates/bevy_openxr/examples/sessions.rs
crates/bevy_openxr/src/openxr/features/handtracking.rs
crates/bevy_openxr/src/openxr/features/passthrough.rs
crates/bevy_openxr/src/openxr/init.rs
crates/bevy_openxr/src/openxr/layer_builder.rs
crates/bevy_openxr/src/openxr/render.rs
crates/bevy_openxr/src/openxr/resources.rs
crates/bevy_openxr/src/openxr/spaces.rs
crates/bevy_openxr/src/openxr/types.rs
crates/bevy_xr/src/spaces.rs
crates/bevy_xr_utils/src/tracking_utils.rs

Move `OxrSpaceSyncSet` into `bevy_mod_xr` and add locate_hands to the new set
Reorganize the Session Configuration a bit, its no fully configured through `OxrSessionConfig`, the chosen config can be queried through `OxrCurrentSessionConfig`

XrSpaceSyncSet and OxrSessionConfig 
